language: python
python:
  - "3.6.4"

before_install:
  - pip3 install -r requirements.txt

script:
  echo "Running linter...";
  flake8 --exclude=*/frontendapp/*;
  echo "Running unit tests for command line application...";
  cd MenuValidator/cli/;
  python3 -m unittest discover menus/;
