export const MENUS_RESPONSE_SUCCESS = 'MENUS_RESPONSE_SUCCESS';
export const MENUS_RESPONSE_ERROR = 'MENUS_RESPONSE_ERROR';
export const MENUS_REQUEST_PENDING = 'MENUS_REQUEST_PENDING';
export const MENUS_IDLE = 'MENUS_IDLE';
